from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from git import Repo
from rich.console import Console

console = Console()

SSH_KEY_NAMES = [
    "id_ed25519",
    "id_rsa",
    "id_ecdsa",
    "id_dsa",
]


def find_ssh_key() -> Path | None:
    ssh_dir = Path.home() / ".ssh"
    if not ssh_dir.is_dir():
        return None
    for name in SSH_KEY_NAMES:
        key_path = ssh_dir / name
        if key_path.exists():
            return key_path
    return None


def ssh_agent_has_keys() -> bool:
    try:
        result = subprocess.run(
            ["ssh-add", "-l"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        return result.returncode == 0 and "SHA256:" in result.stdout
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def test_ssh_github() -> bool:
    try:
        result = subprocess.run(
            ["ssh", "-T", "-o", "StrictHostKeyChecking=no",
             "-o", "BatchMode=yes", "git@github.com"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return "successfully authenticated" in result.stderr.lower()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _ensure_ssh_env() -> dict[str, str]:
    env = os.environ.copy()
    if ssh_agent_has_keys():
        return env
    key = find_ssh_key()
    if key:
        env["GIT_SSH_COMMAND"] = f"ssh -i {key} -o StrictHostKeyChecking=no"
    return env


def _to_ssh_url(url: str) -> str:
    match = re.match(r"https://github\.com/([^/]+)/([^/]+?)(?:\.git)?$", url)
    if match:
        return f"git@github.com:{match.group(1)}/{match.group(2)}.git"
    return url


def _to_https_url(url: str) -> str:
    match = re.match(r"git@github\.com:([^/]+)/([^/]+?)(?:\.git)?$", url)
    if match:
        return f"https://github.com/{match.group(1)}/{match.group(2)}"
    return url


def slugify(title: str) -> str:
    slug = title.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug


def clone_repo(url: str) -> Path:
    tmp_dir = Path(tempfile.mkdtemp(prefix="autofolio_"))

    token = os.environ.get("GITHUB_TOKEN")
    if token and "github.com" in url:
        clone_url = url.replace("https://", f"https://x-access-token:{token}@")
    elif "github.com" in url and test_ssh_github():
        clone_url = _to_ssh_url(url)
        console.print("[dim]Using SSH for clone (key detected).[/dim]")
    else:
        clone_url = url

    console.print(f"[dim]Cloning into {tmp_dir}...[/dim]")
    env = _ensure_ssh_env()
    Repo.clone_from(clone_url, str(tmp_dir), depth=1, env=env)
    console.print("[green]Clone complete.[/green]")
    return tmp_dir


def create_branch(repo_path: Path, project_title: str) -> str:
    slug = slugify(project_title)
    branch_name = f"auto/{slug}"
    repo = Repo(str(repo_path))

    if branch_name in [b.name for b in repo.branches]:
        console.print(f"[yellow]Branch {branch_name} already exists, checking out.[/yellow]")
        repo.git.checkout(branch_name)
    else:
        repo.git.checkout("-b", branch_name)
        console.print(f"[green]Created branch: {branch_name}[/green]")

    return branch_name


def commit_changes(repo_path: Path, project_title: str) -> None:
    repo = Repo(str(repo_path))
    repo.git.add(A=True)

    if not repo.is_dirty(untracked_files=True):
        console.print("[yellow]No changes to commit.[/yellow]")
        return

    message = f"feat: add {project_title} to portfolio\n\nGenerated by AutoFolio"
    repo.index.commit(message)
    console.print(f"[green]Committed: {message.splitlines()[0]}[/green]")


def push_branch(repo_path: Path, branch_name: str) -> None:
    repo = Repo(str(repo_path))
    console.print(f"[dim]Pushing {branch_name} to origin...[/dim]")

    remote_url = ""
    try:
        remote_url = next(repo.remote("origin").urls, "")
    except (ValueError, StopIteration):
        pass

    if "git@" in remote_url or ssh_agent_has_keys() or find_ssh_key():
        env = _ensure_ssh_env()
        with repo.git.custom_environment(**env):
            repo.git.push("origin", branch_name, set_upstream=True)
    else:
        repo.git.push("origin", branch_name, set_upstream=True)

    console.print(f"[green]Pushed {branch_name} to origin.[/green]")


def create_pull_request(
    repo_url: str,
    branch_name: str,
    project_title: str,
    repo_path: Path | None = None,
) -> str | None:
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        return _create_pr_pygithub(repo_url, branch_name, project_title, token)
    return _create_pr_gh_cli(branch_name, project_title, repo_path)


def _create_pr_pygithub(
    repo_url: str, branch_name: str, project_title: str, token: str
) -> str | None:
    try:
        from github import Github
    except ImportError:
        console.print(
            "[yellow]PyGithub not installed, falling back to gh CLI...[/yellow]"
        )
        return _create_pr_gh_cli(branch_name, project_title, None)

    match = re.search(r"github\.com[/:]([^/]+)/([^/.]+)", repo_url)
    if not match:
        console.print(f"[red]Could not parse GitHub owner/repo from: {repo_url}[/red]")
        return None

    owner, repo_name = match.group(1), match.group(2)
    g = Github(token)
    repo = g.get_repo(f"{owner}/{repo_name}")
    default_branch = repo.default_branch

    pr = repo.create_pull(
        title=f"Add {project_title} to portfolio",
        body=(
            f"This PR adds **{project_title}** to the portfolio.\n\n"
            "Generated by [AutoFolio](https://github.com/aringadre76/autofolio)."
        ),
        head=branch_name,
        base=default_branch,
    )
    console.print(f"[green]Pull request created: {pr.html_url}[/green]")
    return pr.html_url


def _create_pr_gh_cli(
    branch_name: str, project_title: str, repo_path: Path | None = None
) -> str | None:
    gh_path = shutil.which("gh")
    if not gh_path:
        home_gh = Path.home() / ".local" / "bin" / "gh"
        if home_gh.exists():
            gh_path = str(home_gh)

    if not gh_path:
        console.print(
            "[red]No GITHUB_TOKEN set and gh CLI not found. "
            "Cannot create PR.[/red]"
        )
        console.print(
            "[dim]Set GITHUB_TOKEN or install/authenticate the gh CLI.[/dim]"
        )
        return None

    title = f"Add {project_title} to portfolio"
    body = (
        f"This PR adds **{project_title}** to the portfolio.\n\n"
        "Generated by [AutoFolio](https://github.com/aringadre76/autofolio)."
    )

    cwd = str(repo_path) if repo_path else None

    result = subprocess.run(
        [gh_path, "pr", "create", "--title", title, "--body", body],
        capture_output=True,
        text=True,
        timeout=30,
        cwd=cwd,
    )

    if result.returncode != 0:
        stderr = result.stderr.strip()
        if "not logged" in stderr or "auth login" in stderr:
            console.print(
                "[red]gh CLI not authenticated. "
                "Run: gh auth login[/red]"
            )
        else:
            console.print(f"[red]gh pr create failed: {stderr}[/red]")
        return None

    pr_url = result.stdout.strip()
    console.print(f"[green]Pull request created: {pr_url}[/green]")
    return pr_url


def get_github_remote_url(repo_path: Path) -> str | None:
    try:
        repo = Repo(str(repo_path))
    except Exception:
        return None

    for remote in repo.remotes:
        for url in remote.urls:
            if "github.com" in url:
                normalized = url
                if normalized.startswith("git@github.com:"):
                    normalized = normalized.replace(
                        "git@github.com:", "https://github.com/"
                    )
                if normalized.endswith(".git"):
                    normalized = normalized[:-4]
                return normalized
    return None


def cleanup_temp(path: Path) -> None:
    if "autofolio_" in str(path) and path.is_dir():
        shutil.rmtree(path, ignore_errors=True)
        console.print(f"[dim]Cleaned up temp directory: {path}[/dim]")
